# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 258b82e14e938c0f9701ed3726a066fcc1774ab45f46a9a6c3fb1bd682aacce713779d6285c3ebfa321207a508e5766f5a7d3498d5d5c0e361b3760b8680a27d

test:
  secret_key_base: 3519a5db6953f1ad060ae15d8cf70c8d7ee89a1abaae03d0d48ac66f17d1214a472fadcd66f861b2a62f685713cf962c0e7396e7dc4e31f13b4dcc26e5aa060c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
